name: Build and Push ARM64 Docker Image

on:
  push:
    branches:
      - main  # 监听 main 分支的推送事件
  pull_request:
    branches:
      - main  # 监听 main 分支的拉取请求事件

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
    # Step 1: Checkout 代码
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: 设置 Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: 登录到 Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # 使用 GitHub Secrets 中的 Docker Hub 用户名
        password: ${{ secrets.DOCKER_PASSWORD }}  # 使用 GitHub Secrets 中的 Docker Hub 密码或 Personal Access Token

    # Step 4: 构建并推送 ARM64 Docker 镜像
    - name: Build and push ARM64 Docker image
      uses: docker/build-push-action@v2
      with:
        context: .  # 使用当前目录作为构建上下文
        file: ./Dockerfile  # 指定 Dockerfile 文件
        push: true  # 推送镜像到 Docker Hub
        tags: whoisbot/localshare:latest  # 镜像的标签，替换为你的 Docker Hub 用户名
        platforms: linux/arm64  # 只为 ARM64 架构构建镜像
