name: Build and Push Docker Image

# 触发条件：每次 push 到 master 或 main 分支时触发
on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: 检出代码
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: 设置 Docker 环境
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: 登录 Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: 构建 Docker 镜像
    - name: Build the Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/localshare-app:latest .

    # Step 5: 推送 Docker 镜像到 Docker Hub
    - name: Push the Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/localshare-app:latest
