name: Build and Push Docker Image for aarch64

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: 检出代码
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: 设置 Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: 登录 Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: 构建 Docker 镜像并指定架构
    - name: Build the Docker image for aarch64
      run: |
        docker buildx build --platform linux/arm64,linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/localshare-app:latest --push .

    # Step 5: 推送 Docker 镜像
    - name: Push the Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/localshare-app:latest
